[phases.setup]
nixPkgs = ['nodejs_18', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'npm install',
    'cd server && npm install', 
    'cd server/python && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build completed successfully"']

[start]
cmd = 'node start-services.js'

[variables]
NODE_ENV = 'production'
PORT = '5000'
