[build]
builder = "NIXPACKS"

[build.nixpacksConfigPath]

[deploy]
startCommand = "node start-services.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
