nixpacks.toml
[phases.setup]
nixPkgs = ['nodejs_18', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'cd server && npm install',
    'cd python && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'cd server && npm start'
